apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - image: nginx
    name: hostpath-pod
    volumeMounts:
    - mountPath: /host-path
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /
