apiVersion: v1
kind: Pod
metadata:
  name: non-root
spec:
   containers:
   - name: myshell
     image: "ubuntu:14.04"
     command:
       - /bin/sleep
       - "300"
     securityContext:
      runAsNonRoot: true