apiVersion: v1
kind: Pod
metadata:
  name: priv-esc-pod
spec:
  containers:
  - name: sec-ctx-demo
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      allowPrivilegeEscalation: true